services:
  eb-frontend:
    build: ./frontend
    image: eb-microservices-demo-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - eb-java-service
      - eb-python-service
    networks:
      - app-network

  eb-java-service:
    build: ./java-service
    image: eb-microservices-demo-java-service:latest
    ports:
      - "8080:8080"
    environment:
      - PYTHON_SERVICE_URL=http://eb-python-service:5000
      - OTEL_SERVICE_NAME=eb-java-service
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://eb-alloy:4317
      - OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED=true
      - JAVA_TOOL_OPTIONS=-javaagent:/app/opentelemetry-java-instrumentation.jar
      - OTEL_RESOURCE_ATTRIBUTES=service.name=eb-java-service,service.namespace=eb-microservices,service.instance.id=java-1
      - PYROSCOPE_USERNAME=${PYROSCOPE_USERNAME}
      - PYROSCOPE_PASSWORD=${PYROSCOPE_PASSWORD}
      - PYROSCOPE_SERVER_ADDRESS=https://profiles-prod-003.grafana.net
      - PYROSCOPE_APPLICATION_NAME=eb-java-service
    networks:
      - app-network

  eb-python-service:
    build: ./python-service
    image: eb-microservices-demo-python-service:latest
    ports:
      - "5000:5000"
    environment:
      - JAVA_SERVICE_URL=http://eb-java-service:8080
      - OTEL_SERVICE_NAME=eb-python-service
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://eb-alloy:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_PYTHON_FLASK_EXCLUDED_URLS=""
      - OTEL_LOG_LEVEL=debug
      - OTEL_RESOURCE_ATTRIBUTES=service.name=eb-python-service,service.namespace=eb-microservices,service.instance.id=python-1
      - PYROSCOPE_USERNAME=${PYROSCOPE_USERNAME}
      - PYROSCOPE_PASSWORD=${PYROSCOPE_PASSWORD}
      - PYROSCOPE_SERVER_ADDRESS=https://profiles-prod-003.grafana.net
      - PYROSCOPE_APPLICATION_NAME=eb-python-service
    networks:
      - app-network

  eb-load-testing:
    build:
      context: ./load-testing
      dockerfile: Dockerfile
    image: eb-microservices-demo-load-testing:latest
    environment:
      - LOAD_TEST_DURATION=300
      - LOAD_TEST_USERS=50
      - LOAD_TEST_SPAWN_RATE=5
      - LOCUST_HOST=http://eb-frontend
    ports:
      - "8089:8089"
    networks:
      - app-network
    depends_on:
      - eb-frontend
      - eb-python-service
      - eb-java-service

  eb-alloy:
    image: grafana/alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command: ["run", "--server.http.listen-addr=0.0.0.0:12346", "--storage.path=/var/lib/alloy/data", "--stability.level=public-preview", "/etc/alloy/config.alloy"]
    ports:
      - "12346:12346"
      - "4317:4317"
      - "4318:4318"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
