apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deployment.yaml
  - python-service-deployment.yaml
  - java-service-deployment.yaml
  - load-testing-deployment.yaml
  - ingress.yaml
