apiVersion: v2
name: microservices-demo
description: A Helm chart for the Microservices Demo application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
